language: php

php:
  - 7
  - 5.6

cache:
  directories:
    - $HOME/.composer/cache

env:
  - LARAVEL_VERSION="~5.3" TESTBENCH_VERSION="~3.3"

before_script:
  - chmod +x travis.sh
  - ./travis.sh

script: phpunit

sudo: false

